Funcionalidad de recuperar clave
FernandoAndresColina/andromeda pull request #1
Opened 2023-11-28 00:32 UTC by FernandoAndresColina

- Archivo HTML
- Funcionalidad de envios de correos
- Confirmar cotraseña

2023-11-28 14:52 UTC, FernandoAndresColina commented on claves.txt
> +miclave
Se ve bien! Pero podrias dejar "miclave" separado? "Mi clave".

2023-11-29 22:40 UTC, FernandoAColina commented on claves.txt
> +mi clave
Se ve bien! Pero podrías dejar "miclave" separado? como "mi clave"

2023-11-29 22:42 UTC, FernandoAColina requested changes
Por favor actualizar archivo.txt

2023-11-29 22:51 UTC, FernandoAndresColina commented on claves.txt
> +mi clave
Cambio realizado! Por favor revisar de nuevo

2023-11-29 22:55 UTC, FernandoAColina approved these changes
LGTM!🚀

2023-12-02 23:06 UTC, closed without merging